- CDS Installation

diff --git a/portal/Dockerfile b/portal/Dockerfile
--- a/portal/Dockerfile
+++ b/portal/Dockerfile
@@ -1,20 +1,21 @@
 FROM centos:7
+
 ARG STAGE_NAME="Mgmt"
+
 ARG USER=opentext
 ARG UID=1000
 ARG GID=1000
 # default password for user
 ARG PW=opentext
 RUN useradd -m ${USER} --uid=${UID} && echo "${USER}:${PW}" | \
-      chpasswd
-
+    chpasswd
 
 ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
 
-RUN yum install -y tzdata openssl curl ca-certificates fontconfig gzip tar unzip \
+RUN yum install -y tzdata openssl curl ca-certificates fontconfig gzip tar unzip hostname vim \
     && yum update -y; yum clean all
 
-# AdoptJDK
+# AdoptOpenJDK
 ENV JAVA_VERSION jdk8u265-b01
 
 
@@ -52,136 +53,169 @@ ENV TOMCAT_VERSION 9.0.37
 ENV TOMCAT_SHA512 077c3e69553b9388b5cdf46b6d204e895d69629a4ec8dd8cf13eb2ee97a04f50e70478fee4f2f91e8809b85bdcd3656188b00d17165c86cf6113ded18729ba06
 
 RUN set -eux; \
-	\
-# http://yum.baseurl.org/wiki/YumDB.html
-	if ! command -v yumdb > /dev/null; then \
-		yum install -y yum-utils; \
-		yumdb set reason dep yum-utils; \
-	fi; \
-# a helper function to "yum install" things, but only if they aren't installed (and to set their "reason" to "dep" so "yum autoremove" can purge them for us)
-	_yum_install_temporary() { ( set -eu +x; \
-		local pkg todo=''; \
-		for pkg; do \
-			if ! rpm --query "$pkg" > /dev/null 2>&1; then \
-				todo="$todo $pkg"; \
-			fi; \
-		done; \
-		if [ -n "$todo" ]; then \
-			set -x; \
-			yum install -y $todo; \
-			yumdb set reason dep $todo; \
-		fi; \
-	) }; \
-	_yum_install_temporary gzip tar; \
-	\
-	ddist() { \
-		local f="$1"; shift; \
-		local distFile="$1"; shift; \
-		local mvnFile="${1:-}"; \
-		local success=; \
-		local distUrl=; \
-		for distUrl in \
-# https://issues.apache.org/jira/browse/INFRA-8753?focusedCommentId=14735394#comment-14735394
-			"https://www.apache.org/dyn/closer.cgi?action=download&filename=$distFile" \
-# if the version is outdated (or we're grabbing the .asc file), we might have to pull from the dist/archive :/
-			"https://www-us.apache.org/dist/$distFile" \
-			"https://www.apache.org/dist/$distFile" \
-			"https://archive.apache.org/dist/$distFile" \
-# if all else fails, let's try Maven (https://www.mail-archive.com/users@tomcat.apache.org/msg134940.html; https://mvnrepository.com/artifact/org.apache.tomcat/tomcat; https://repo1.maven.org/maven2/org/apache/tomcat/tomcat/)
-			${mvnFile:+"https://repo1.maven.org/maven2/org/apache/tomcat/tomcat/$mvnFile"} \
-		; do \
-			if curl -fL -o "$f" "$distUrl" && [ -s "$f" ]; then \
-				success=1; \
-				break; \
-			fi; \
-		done; \
-		[ -n "$success" ]; \
-	}; \
-	\
-	ddist 'tomcat.tar.gz' "tomcat/tomcat-$TOMCAT_MAJOR/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz" "$TOMCAT_VERSION/tomcat-$TOMCAT_VERSION.tar.gz"; \
-	echo "$TOMCAT_SHA512 *tomcat.tar.gz" | sha512sum --strict --check -; \
-	ddist 'tomcat.tar.gz.asc' "tomcat/tomcat-$TOMCAT_MAJOR/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz.asc" "$TOMCAT_VERSION/tomcat-$TOMCAT_VERSION.tar.gz.asc"; \
-	export GNUPGHOME="$(mktemp -d)"; \
-	for key in $GPG_KEYS; do \
-		gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
-	done; \
-	gpg --batch --verify tomcat.tar.gz.asc tomcat.tar.gz; \
-	tar -xf tomcat.tar.gz --strip-components=1; \
-	rm bin/*.bat; \
-	rm tomcat.tar.gz*; \
-	command -v gpgconf && gpgconf --kill all || :; \
-	rm -rf "$GNUPGHOME"; \
-	\
-# https://tomcat.apache.org/tomcat-9.0-doc/security-howto.html#Default_web_applications
-	mv webapps webapps.dist; \
-	mkdir webapps; \
-# we don't delete them completely because they're frankly a pain to get back for users who do want them, and they're generally tiny (~7MB)
-	\
-	nativeBuildDir="$(mktemp -d)"; \
-	tar -xf bin/tomcat-native.tar.gz -C "$nativeBuildDir" --strip-components=1; \
-	_yum_install_temporary \
-		apr-devel \
-		gcc \
-		make \
-		openssl-devel \
-	; \
-	( \
-		export CATALINA_HOME="$PWD"; \
-		cd "$nativeBuildDir/native"; \
-		aprConfig="$(command -v apr-1-config)"; \
-		./configure \
-			--libdir="$TOMCAT_NATIVE_LIBDIR" \
-			--prefix="$CATALINA_HOME" \
-			--with-apr="$aprConfig" \
-			--with-java-home="$JAVA_HOME" \
-			--with-ssl=yes; \
-		make -j "$(nproc)"; \
-		make install; \
-	); \
-	rm -rf "$nativeBuildDir"; \
-	rm bin/tomcat-native.tar.gz; \
-	\
-# mark any explicit dependencies as manually installed
-	deps="$( \
-		find "$TOMCAT_NATIVE_LIBDIR" -type f -executable -exec ldd '{}' ';' \
-			| awk '/=>/ && $(NF-1) != "=>" { print $(NF-1) }' \
-			| sort -u \
-			| xargs -r rpm --query --whatprovides \
-			| sort -u \
-	)"; \
-	[ -z "$deps" ] || yumdb set reason user $deps; \
-	\
-# clean up anything added temporarily and not later marked as necessary
-	yum autoremove -y; \
-	yum clean all; \
-	rm -rf /var/cache/yum; \
-	\
-# sh removes env vars it doesn't support (ones with periods)
-# https://github.com/docker-library/tomcat/issues/77
-	find ./bin/ -name '*.sh' -exec sed -ri 's|^#!/bin/sh$|#!/usr/bin/env bash|' '{}' +; \
-	\
-# fix permissions (especially for running as non-root)
-# https://github.com/docker-library/tomcat/issues/35
-	chmod -R +rX .; \
-	chmod 777 logs temp work
+    \
+    # http://yum.baseurl.org/wiki/YumDB.html
+    if ! command -v yumdb > /dev/null; then \
+    yum install -y yum-utils; \
+    yumdb set reason dep yum-utils; \
+    fi; \
+    # a helper function to "yum install" things, but only if they aren't installed (and to set their "reason" to "dep" so "yum autoremove" can purge them for us)
+    _yum_install_temporary() { ( set -eu +x; \
+    local pkg todo=''; \
+    for pkg; do \
+    if ! rpm --query "$pkg" > /dev/null 2>&1; then \
+    todo="$todo $pkg"; \
+    fi; \
+    done; \
+    if [ -n "$todo" ]; then \
+    set -x; \
+    yum install -y $todo; \
+    yumdb set reason dep $todo; \
+    fi; \
+    ) }; \
+    _yum_install_temporary gzip tar; \
+    \
+    ddist() { \
+    local f="$1"; shift; \
+    local distFile="$1"; shift; \
+    local mvnFile="${1:-}"; \
+    local success=; \
+    local distUrl=; \
+    for distUrl in \
+    # https://issues.apache.org/jira/browse/INFRA-8753?focusedCommentId=14735394#comment-14735394
+    "https://www.apache.org/dyn/closer.cgi?action=download&filename=$distFile" \
+    # if the version is outdated (or we're grabbing the .asc file), we might have to pull from the dist/archive :/
+    "https://www-us.apache.org/dist/$distFile" \
+    "https://www.apache.org/dist/$distFile" \
+    "https://archive.apache.org/dist/$distFile" \
+    # if all else fails, let's try Maven (https://www.mail-archive.com/users@tomcat.apache.org/msg134940.html; https://mvnrepository.com/artifact/org.apache.tomcat/tomcat; https://repo1.maven.org/maven2/org/apache/tomcat/tomcat/)
+    ${mvnFile:+"https://repo1.maven.org/maven2/org/apache/tomcat/tomcat/$mvnFile"} \
+    ; do \
+    if curl -fL -o "$f" "$distUrl" && [ -s "$f" ]; then \
+    success=1; \
+    break; \
+    fi; \
+    done; \
+    [ -n "$success" ]; \
+    }; \
+    \
+    ddist 'tomcat.tar.gz' "tomcat/tomcat-$TOMCAT_MAJOR/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz" "$TOMCAT_VERSION/tomcat-$TOMCAT_VERSION.tar.gz"; \
+    echo "$TOMCAT_SHA512 *tomcat.tar.gz" | sha512sum --strict --check -; \
+    ddist 'tomcat.tar.gz.asc' "tomcat/tomcat-$TOMCAT_MAJOR/v$TOMCAT_VERSION/bin/apache-tomcat-$TOMCAT_VERSION.tar.gz.asc" "$TOMCAT_VERSION/tomcat-$TOMCAT_VERSION.tar.gz.asc"; \
+    export GNUPGHOME="$(mktemp -d)"; \
+    for key in $GPG_KEYS; do \
+    gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
+    done; \
+    gpg --batch --verify tomcat.tar.gz.asc tomcat.tar.gz; \
+    tar -xf tomcat.tar.gz --strip-components=1; \
+    rm bin/*.bat; \
+    rm tomcat.tar.gz*; \
+    command -v gpgconf && gpgconf --kill all || :; \
+    rm -rf "$GNUPGHOME"; \
+    \
+    # https://tomcat.apache.org/tomcat-9.0-doc/security-howto.html#Default_web_applications
+    mv webapps webapps.dist; \
+    mkdir webapps; \
+    # we don't delete them completely because they're frankly a pain to get back for users who do want them, and they're generally tiny (~7MB)
+    \
+    nativeBuildDir="$(mktemp -d)"; \
+    tar -xf bin/tomcat-native.tar.gz -C "$nativeBuildDir" --strip-components=1; \
+    _yum_install_temporary \
+    apr-devel \
+    gcc \
+    make \
+    openssl-devel \
+    ; \
+    ( \
+    export CATALINA_HOME="$PWD"; \
+    cd "$nativeBuildDir/native"; \
+    aprConfig="$(command -v apr-1-config)"; \
+    ./configure \
+    --libdir="$TOMCAT_NATIVE_LIBDIR" \
+    --prefix="$CATALINA_HOME" \
+    --with-apr="$aprConfig" \
+    --with-java-home="$JAVA_HOME" \
+    --with-ssl=yes; \
+    make -j "$(nproc)"; \
+    make install; \
+    ); \
+    rm -rf "$nativeBuildDir"; \
+    rm bin/tomcat-native.tar.gz; \
+    \
+    # mark any explicit dependencies as manually installed
+    deps="$( \
+    find "$TOMCAT_NATIVE_LIBDIR" -type f -executable -exec ldd '{}' ';' \
+    | awk '/=>/ && $(NF-1) != "=>" { print $(NF-1) }' \
+    | sort -u \
+    | xargs -r rpm --query --whatprovides \
+    | sort -u \
+    )"; \
+    [ -z "$deps" ] || yumdb set reason user $deps; \
+    \
+    # clean up anything added temporarily and not later marked as necessary
+    yum autoremove -y; \
+    yum clean all; \
+    rm -rf /var/cache/yum; \
+    \
+    # sh removes env vars it doesn't support (ones with periods)
+    # https://github.com/docker-library/tomcat/issues/77
+    find ./bin/ -name '*.sh' -exec sed -ri 's|^#!/bin/sh$|#!/usr/bin/env bash|' '{}' +; \
+    \
+    # fix permissions (especially for running as non-root)
+    # https://github.com/docker-library/tomcat/issues/35
+    chmod -R +rX .; \
+    chmod 777 logs temp work
 
 # verify Tomcat Native is working properly
 RUN set -e \
-	&& nativeLines="$(catalina.sh configtest 2>&1)" \
-	&& nativeLines="$(echo "$nativeLines" | grep 'Apache Tomcat Native')" \
-	&& nativeLines="$(echo "$nativeLines" | sort -u)" \
-	&& if ! echo "$nativeLines" | grep -E 'INFO: Loaded( APR based)? Apache Tomcat Native library' >&2; then \
-		echo >&2 "$nativeLines"; \
-		exit 1; \
-	fi
-
-
+    && nativeLines="$(catalina.sh configtest 2>&1)" \
+    && nativeLines="$(echo "$nativeLines" | grep 'Apache Tomcat Native')" \
+    && nativeLines="$(echo "$nativeLines" | sort -u)" \
+    && if ! echo "$nativeLines" | grep -E 'INFO: Loaded( APR based)? Apache Tomcat Native library' >&2; then \
+    echo >&2 "$nativeLines"; \
+    exit 1; \
+    fi
 
 # Portal
 COPY opentext_portal_for_unix.bin /opentext/distrib/
+
 RUN chmod 770 /opentext/distrib/opentext_portal_for_unix.bin
 
-RUN chown -R ${USER} /opentext;
+COPY silent/portal.properties /opentext/distrib/
+
+RUN set -eux; \
+    \
+    cd /opentext/distrib/; \
+    ./opentext_portal_for_unix.bin -i silent -f portal.properties;
+
+# CDS
+COPY setup_linux64_cds_16_2_2.bin /opentext/distrib/
+
+RUN chmod 770 /opentext/distrib/setup_linux64_cds_16_2_2.bin
+
+COPY silent/cds.properties /opentext/distrib/
+
+RUN set -eux; \
+    \
+    cd /opentext/distrib/; \
+    ./setup_linux64_cds_16_2_2.bin -i silent -f cds.properties;
+
+RUN cd /opentext/ot/CDS/Content/16_2/bin; \
+    ./vgncdawar.sh -a tomcat -c dpm -webapi yes -otds yes -samplesite yes;
+
+RUN mkdir -p /opentext/otwork/CDS/classpath/; \
+    cp /opentext/ot/CDS/Content/16_2/lib/sdk/custom-apps/cda-classpath/* /opentext/otwork/CDS/classpath/; 
+
+RUN cp /opentext/ot/CDS/Content/16_2/lib/sdk/custom-apps/tomcat-dpm/sites.war $CATALINA_HOME/webapps; \
+    cp /opentext/ot/CDS/Content/16_2/lib/sdk/custom-apps/tomcat-dpm/vgn-tas.war $CATALINA_HOME/webapps; \
+    cp /opentext/ot/CDS/Content/16_2/lib/sdk/custom-apps/tomcat-dpm/vgn-innovate.war $CATALINA_HOME/webapps; 
+
+RUN cd /opentext/ot/CDS/Content/16_2/bin; \
+    ./vgncdawar.sh -clean;
+
+RUN rm -Rf /opentext/distrib/setup_linux64_cds_16_2_2.bin
+
+RUN chown -R ${USER}:${USER} /opentext;
 
 USER ${UID}:${GID}
 
